apiVersion: apps/v1
kind: Deployment
metadata:
        name: rabbitmq-partial
        labels:
                app: rabbitmq-partial
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: rabbitmq-partial
        template:
                metadata:
                        labels:
                                app: rabbitmq-partial
                spec:
                        containers:
                                - name: rabbitmq
                                  image: rabbitmq:latest
                                  ports:
                                          - containerPort: 5672



---
apiVersion: v1
kind: Service
metadata:
        name: rabbitmq-partial-service
        labels:
                app: rabbitmq-partial-service
spec:
        type: LoadBalancer
        ports:
                - port: 30021
                  targetPort: 5672
                  nodePort: 30121
        selector:
                app: rabbitmq-partial
