apiVersion: apps/v1
kind: Deployment
metadata:
        name: streamingestmanager-partial
        labels:
                app: streamingestmanager-partial
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: streamingestmanager-partial
        template:
                metadata:
                        labels:
                                app: streamingestmanager-partial
                spec:
                        containers:
                                - name: streamingestmanager-partial
                                  image: gcr.io/my-project-hello-world-255117/streamingestmanager-partial:v0.13
                                  ports:
                                          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
        name: streamingestmanager-partial-service
        labels:
                app: streamingestmanager-partial-service
spec:
        selector:
                app: streamingestmanager-partial
        ports:
                - port: 30023
                  protocol: TCP
                  targetPort: 80
                  nodePort: 30123
        type: LoadBalancer
