apiVersion: apps/v1
kind: Deployment
metadata:
        name: data-broker
        labels:
                app: data-broker
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: data-broker
        template:
                metadata:
                        labels:
                                app: data-broker
                spec:
                        containers:
                                - name: mysimbdp-data-broker
                                  image: gcr.io/my-project-hello-world-255117/mysimbdp-data-broker:v0.15
                                  ports:
                                          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
        name: data-broker-service
        labels:
                app: data-broker-service
spec:
        selector:
                app: data-broke-batch
        ports:
                - port: 30010
                  protocol: TCP
                  targetPort: 80
                  nodePort: 30110
        type: LoadBalancer
