apiVersion: apps/v1
kind: Deployment
metadata:
        name: rabbitmq
        labels:
                app: rabbitmq
spec:
        replicas: 1
        selectors:
                matchLabels:
                        app: rabbitmq
        template:
                metadata:
                        labels:
                                app: rabbitmq
                spec:
                        containers:
                                - name: rabbitmq
                                  image: rabbitmq:latest
                                  ports:
                                          containerPort: 5672



---
apiVersion: v1
kind: Service
metadata:
        name: rabbitmq-service
        labels:
                app: rabbitmq-service
spec:
        type: LoadBalancer
        ports:
                - port: 30015
                  targetPort: 5672
                  nodePort: 30115
        selector:
                app: rabbitmq
