apiVersion: apps/v1
kind: Deployment
metadata:
        name: mongodb-partial
        labels:
                app: mongodb-partial
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: mongodb-partial
        template:
                metadata:
                        labels:
                                app: mongodb-partial
                spec:
                        containers:
                                - name: mongodb
                                  image: mongo:latest
                                  ports:
                                          - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
        name: mongodb-partial-service
        labels:
                app: mongodb-partial-service
spec:
        type: LoadBalancer
        ports:
                - port: 30020
                  targetPort: 27017
                  nodePort: 30120
        selector:
                app: mongodb-partial
